version: "3.2"

services:
  
  app:
    image: einfachambulant/webportal:latest
    restart: unless-stopped

    environment:
      EA_COUCHDB_URL: http://db:5984
    
    ports:
      - "5000:5000"
    
  db:
    image: couchdb:2.1
    restart: unless-stopped

    volumes:
      - ./data:/opt/couchdb/data
